'use strict';
angular.module('saintApp').service('CaseListEntity',[ 'QueryBuilderEntity', function (QueryBuilderEntity) {
  return {
    'baseCaseListKey': null,
    'caseListName': '',
    'description': '',
    'casesCount': null,
    'isLocked': null,
    'createdBy': null,
    'createdDate': null,
    'updatedBy': null,
    'updatedDate': null,
    'isCCL': null,
    'queryFilter': null,
    'allDatesFlag': null,
    'reportingStartDate': null,
    'reportingEndDate': null,
    'asOfDate': null,
    'submissionDueDate': null,
    'nsMedwatchReportsFlag': null,
    'casesNtPreRptdFlag': null,
    'eventReceiptDate': false,
    'initialReceiptDate': false,
    'followupReceiptDate': false,
    'iCSRSubmissionDate': false,
    'otherDateFlag': false,
    'signalCompStartDate': null,
    'signalCompEndDate': null,
    'signalCumlStartDate': null,
    'signalCumlEndDate': null,
    'signalThreshold': null,
    'signalDenomCaseFlag': null,
    'signalDenomOtherFlag': null,
    'signalDenominator': null,
    'routedDateFlag': false,
    'caseCompletionDateFlag': false,
    'comparatorPeriodKey': null,
    'productLicenseOption': 0,
    'runTime': null,
    'runDate': null,
    'caseListDisplayName': '',
    'products': [],
    'licenses': [],
    'caseListId': null,
    'finalQuery': '',
    'reportType': null,
    'ingredient': null,
    'licenseKey': null,
    'isFavorite': false,
    'dataLockPoint': false,
    'caseSubmissionDate': false,
    'cases': [],
    'sourceFilter': null,
    'analyticalFilter': null,
    'sourceCasesCount': 0,
    'analyticalCasesCount': 0,
    'taskKey': null,
    'queryCaseCriteria': null,
    'creationDate': null,
    'caseListFilters': [],
    'contents':[],
    'selectedFilters':[],
    'querySets': [],
    'queryBuilderObject': angular.copy(QueryBuilderEntity),
    'caseNumber':null,
    'caseListSort': {
      'sortedBy': null,
      'sortedByName': null,
      'sortOrder': null,
      'secondarySort':null
    },
    'primarySort': null,
    'secondarySort':null,
    'listed':0,
    'added':0,
    'removed':0,
    'annotated':0,
    'source': 0,
    'analytical': 0,
    'lastRun': 0,
    'lastSaved': 0,
    'saveFlag': 0,
    'payloadProduct': [],
    'payloadLicense': [],
    'queryFilterUI': null,
    'sourceQueryUI': null,
    'reportKey': null,
    'reportTypeName': '',
    'caseListMode': null,
    'visualQueryFilterUI': null,
    'queryString': '',
    'isShared': null
  };
}]);
